---
version: '3.7'
services:
  bugyi.lib:
    build:
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/bugyi/lib:delegated
    working_dir: /bugyi/lib
    environment:
      - BETTER_EXCEPTIONS
      - CC_REPO_URL
